spring:
  application:
    name: joblisting
  data:
    mongodb:
      uri: mongodb+srv://nawodyaonline:NklV0vZ7lVq7uEkf@cluster0.smk7c.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: incognito